# pdf_generator.py
# Generates secure M-PESA statements

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.pdfencrypt import StandardEncryption
from datetime import datetime


def generate_mpesa_pdf(
    transactions,
    min_income: int,
    min_expenditure: int,
    password: str
):
    file_name = "M-Ledger-AI_Mpesa_Statement.pdf"

    encrypt = StandardEncryption(
        userPassword=password,
        ownerPassword="ledger-admin",
        canPrint=1
    )

    doc = SimpleDocTemplate(
        file_name,
        pagesize=A4,
        encrypt=encrypt
    )

    styles = getSampleStyleSheet()
    elements = []

    # Header
    elements.append(Paragraph("<b>M-Ledger AI</b>", styles["Title"]))
    elements.append(Paragraph("Agentic M-PESA Statement", styles["Heading2"]))
    elements.append(Spacer(1, 12))

    # Metadata
    elements.append(Paragraph(
        f"""
        <b>Statement Period:</b> January 2025<br/>
        <b>Minimum Income:</b> KES {min_income}<br/>
        <b>Minimum Expenditure:</b> KES {min_expenditure}<br/>
        <b>Generated On:</b> {datetime.now().strftime('%Y-%m-%d %H:%M')}
        """,
        styles["Normal"]
    ))

    elements.append(Spacer(1, 14))

    # Filtered transactions
    filtered = [
        [d, r, t, desc, f"KES {amt}"]
        for d, r, t, desc, amt in transactions
        if (t == "Income" and amt >= min_income)
        or (t == "Expenditure" and amt >= min_expenditure)
    ]

    table = Table(
        [["Date", "Receipt", "Type", "Description", "Amount"]] + filtered,
        colWidths=[70, 90, 80, 150, 80]
    )

    table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 1, colors.grey),
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("FONT", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (-1, 1), (-1, -1), "RIGHT"),
    ]))

    elements.append(table)
    elements.append(Spacer(1, 16))

    elements.append(Paragraph(
        "This statement was generated by an Agentic AI system using locally stored "
        "M-PESA transaction data captured via Daraja callbacks.",
        styles["Normal"]
    ))

    doc.build(elements)

    return file_name
